openapi: 3.0.1
info:
  title: PlantMD
  description: This is the documentation for the backend API supporting PlantMD.
  contact:
    email: rachitb@gatech.edu
  version: 0.0.1
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- url: https://crincs-dot-thinger.ue.r.appspot.com
  description: Google Cloud temporary URL
tags:
- name: group
  description: Endpoints related to group management
paths:
  /group:
    put:
      tags:
        - group
      summary: Creates a group for the user
      operationId: create_group
      description: The user must be registered and logged in to use this endpoint.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Group'
        required: true
      responses:
        200:
          description: Group created successfully
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Group'
                  - $ref: '#/components/schemas/GroupHiddenDetails'
        401:
          description: User unauthorized / Bearer token expired
          content: {}
        422:
          description: Group name already exists
          content: {}
    get:
      tags:
        - group
      summary: Gets a list of diseases the user is a part / owner of
      operationId: get_all_groups
      description: The user must be registered and logged in to use this endpoint.
      responses:
        200:
          description: List of diseases the user is a part / owner of
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GroupArray'
        401:
          description: User unauthorized / Bearer token expired
          content: {}

components:
  schemas:
    GroupID:
      type: object
      required:
        - id
      properties:
        id:
          type: integer
          description: Internal ID of the group, as seen in the database
          format: int64
    Group:
      type: object
      required:
        - name
      properties:
        id:
          type: integer
          description: Internal ID of the group, as seen in the database
          format: int64
        name:
          type: string
          description: Short description of the group
          minLength: 3
          maxLength: 128
    GroupHiddenDetails:
      type: object
      properties:
        creation_time:
          type: string
          description: DateTime of the group's creation time
          format: date-time
        is_active:
          type: boolean
          description: Flag denoting whether or not is a group active
    GroupArray:
      type: object
      required:
        - name
      properties:
        groups:
          type: array
          description: An array of group objects
          items:
            $ref: '#/components/schemas/Group'


  securitySchemes:
    userAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
